
create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  titulo text,
  imagem_url text,
  created_at timestamptz not null default now()
);
alter table public.banners enable row level security;
drop policy if exists "banners: leitura publica" on public.banners;
create policy "banners: leitura publica" on public.banners for select to anon, authenticated using (true);
drop policy if exists "banners: insert autenticado" on public.banners;
create policy "banners: insert autenticado" on public.banners for insert to authenticated with check (true);
drop policy if exists "banners: delete autenticado" on public.banners;
create policy "banners: delete autenticado" on public.banners for delete to authenticated using (true);

-- ============================================================
-- 2) SELOS / PARCEIROS
-- ============================================================
create table if not exists public.selos (
  id bigint generated by default as identity primary key,
  nome text not null,
  imagem_url text,
  created_at timestamptz not null default now()
);
alter table public.selos enable row level security;
drop policy if exists "selos: leitura publica" on public.selos;
create policy "selos: leitura publica" on public.selos for select to anon, authenticated using (true);
drop policy if exists "selos: insert autenticado" on public.selos;
create policy "selos: insert autenticado" on public.selos for insert to authenticated with check (true);
drop policy if exists "selos: delete autenticado" on public.selos;
create policy "selos: delete autenticado" on public.selos for delete to authenticated using (true);

-- ============================================================
-- 3) DEPOIMENTOS
-- ============================================================
create table if not exists public.depoimentos (
  id bigint generated by default as identity primary key,
  nome text not null,
  instagram text,
  video_url text,
  foto_url text,
  created_at timestamptz not null default now()
);
alter table public.depoimentos enable row level security;
drop policy if exists "depoimentos: leitura publica" on public.depoimentos;
create policy "depoimentos: leitura publica" on public.depoimentos for select to anon, authenticated using (true);
drop policy if exists "depoimentos: insert autenticado" on public.depoimentos;
create policy "depoimentos: insert autenticado" on public.depoimentos for insert to authenticated with check (true);
drop policy if exists "depoimentos: delete autenticado" on public.depoimentos;
create policy "depoimentos: delete autenticado" on public.depoimentos for delete to authenticated using (true);

-- ============================================================
-- 4) DIFERENCIAIS
-- ============================================================
create table if not exists public.diferenciais (
  id bigint generated by default as identity primary key,
  titulo text not null,
  imagem_url text,
  created_at timestamptz not null default now()
);
alter table public.diferenciais enable row level security;
drop policy if exists "diferenciais: leitura publica" on public.diferenciais;
create policy "diferenciais: leitura publica" on public.diferenciais for select to anon, authenticated using (true);
drop policy if exists "diferenciais: insert autenticado" on public.diferenciais;
create policy "diferenciais: insert autenticado" on public.diferenciais for insert to authenticated with check (true);
drop policy if exists "diferenciais: delete autenticado" on public.diferenciais;
create policy "diferenciais: delete autenticado" on public.diferenciais for delete to authenticated using (true);

-- ============================================================
-- 5) NOTICIAS (Blog)
-- ============================================================
create table if not exists public.noticias (
  id bigint generated by default as identity primary key,
  titulo text not null,
  resumo text,
  imagem_url text,
  destaque boolean not null default false,
  tempo_leitura integer not null default 3,
  created_at timestamptz not null default now()
);
alter table public.noticias enable row level security;
drop policy if exists "noticias: leitura publica" on public.noticias;
create policy "noticias: leitura publica" on public.noticias for select to anon, authenticated using (true);
drop policy if exists "noticias: insert autenticado" on public.noticias;
create policy "noticias: insert autenticado" on public.noticias for insert to authenticated with check (true);
drop policy if exists "noticias: delete autenticado" on public.noticias;
create policy "noticias: delete autenticado" on public.noticias for delete to authenticated using (true);

-- ============================================================
-- 6) FAQS
-- ============================================================
create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  pergunta text not null,
  resposta text not null,
  topico text not null default 'Geral',
  created_at timestamptz not null default now()
);
alter table public.faqs enable row level security;
drop policy if exists "faqs: leitura publica" on public.faqs;
create policy "faqs: leitura publica" on public.faqs for select to anon, authenticated using (true);
drop policy if exists "faqs: insert autenticado" on public.faqs;
create policy "faqs: insert autenticado" on public.faqs for insert to authenticated with check (true);
drop policy if exists "faqs: delete autenticado" on public.faqs;
create policy "faqs: delete autenticado" on public.faqs for delete to authenticated using (true);

-- ============================================================
-- 7) VAGAS
-- ============================================================
create table if not exists public.vagas (
  id bigint generated by default as identity primary key,
  titulo text not null,
  departamento text,
  localizacao text,
  tipo_contrato text default 'CLT',
  descricao text not null,
  link_formulario text,
  created_at timestamptz not null default now()
);
alter table public.vagas enable row level security;
drop policy if exists "vagas: leitura publica" on public.vagas;
create policy "vagas: leitura publica" on public.vagas for select to anon, authenticated using (true);
drop policy if exists "vagas: insert autenticado" on public.vagas;
create policy "vagas: insert autenticado" on public.vagas for insert to authenticated with check (true);
drop policy if exists "vagas: delete autenticado" on public.vagas;
create policy "vagas: delete autenticado" on public.vagas for delete to authenticated using (true);

-- ============================================================
-- 8) CURSOS EM DESTAQUE (substitui o endpoint /api/cursos do Strapi/Render)
-- ============================================================
create table if not exists public.cursos_destaque (
  id bigint generated by default as identity primary key,
  titulo text not null,
  resumo text,
  duracao text,
  categoria text,
  imagem_url text,
  created_at timestamptz not null default now()
);
alter table public.cursos_destaque enable row level security;
drop policy if exists "cursos_destaque: leitura publica" on public.cursos_destaque;
create policy "cursos_destaque: leitura publica" on public.cursos_destaque for select to anon, authenticated using (true);
drop policy if exists "cursos_destaque: insert autenticado" on public.cursos_destaque;
create policy "cursos_destaque: insert autenticado" on public.cursos_destaque for insert to authenticated with check (true);
drop policy if exists "cursos_destaque: update autenticado" on public.cursos_destaque;
create policy "cursos_destaque: update autenticado" on public.cursos_destaque for update to authenticated using (true) with check (true);
drop policy if exists "cursos_destaque: delete autenticado" on public.cursos_destaque;
create policy "cursos_destaque: delete autenticado" on public.cursos_destaque for delete to authenticated using (true);

-- ============================================================
-- 9) BANNER LATERAL DO BLOG (substitui /api/banner-blog-lateral do Strapi/Render)
-- ============================================================
create table if not exists public.banner_blog_lateral (
  id bigint generated by default as identity primary key,
  imagem_url text,
  link text,
  created_at timestamptz not null default now()
);
alter table public.banner_blog_lateral enable row level security;
drop policy if exists "banner_blog_lateral: leitura publica" on public.banner_blog_lateral;
create policy "banner_blog_lateral: leitura publica" on public.banner_blog_lateral for select to anon, authenticated using (true);
drop policy if exists "banner_blog_lateral: insert autenticado" on public.banner_blog_lateral;
create policy "banner_blog_lateral: insert autenticado" on public.banner_blog_lateral for insert to authenticated with check (true);
drop policy if exists "banner_blog_lateral: delete autenticado" on public.banner_blog_lateral;
create policy "banner_blog_lateral: delete autenticado" on public.banner_blog_lateral for delete to authenticated using (true);

-- ============================================================
-- 10) FOTO "NOSSA HISTÓRIA" (seção da página Sobre Nós)
-- ============================================================
create table if not exists public.sobre_historia (
  id bigint generated by default as identity primary key,
  imagem_url text,
  created_at timestamptz not null default now()
);
alter table public.sobre_historia enable row level security;
drop policy if exists "sobre_historia: leitura publica" on public.sobre_historia;
create policy "sobre_historia: leitura publica" on public.sobre_historia for select to anon, authenticated using (true);
drop policy if exists "sobre_historia: insert autenticado" on public.sobre_historia;
create policy "sobre_historia: insert autenticado" on public.sobre_historia for insert to authenticated with check (true);
drop policy if exists "sobre_historia: delete autenticado" on public.sobre_historia;
create policy "sobre_historia: delete autenticado" on public.sobre_historia for delete to authenticated using (true);

-- ============================================================
-- 11) STORAGE: bucket público "banners"
-- Usado por TODOS os uploads de imagem do painel admin
-- (banners, selos, depoimentos, diferenciais, notícias,
--  cursos em destaque, banner lateral e foto de Nossa História).
-- ============================================================
insert into storage.buckets (id, name, public)
values ('banners', 'banners', true)
on conflict (id) do nothing;

drop policy if exists "banners bucket: leitura publica" on storage.objects;
create policy "banners bucket: leitura publica"
  on storage.objects for select
  to public
  using (bucket_id = 'banners');

drop policy if exists "banners bucket: upload autenticado" on storage.objects;
create policy "banners bucket: upload autenticado"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'banners');

drop policy if exists "banners bucket: delete autenticado" on storage.objects;
create policy "banners bucket: delete autenticado"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'banners');

-- ============================================================
-- 12) CURSOS CADASTRADOS (cards de curso com página de detalhe,
-- cadastrados pelo admin — diferente da lista estática de cursos
-- do código e do "cursos_destaque" da home).
-- ============================================================
create table if not exists public.cursos_cadastrados (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text,
  categoria text,
  preco numeric(10,2) not null default 0,
  preco_original numeric(10,2),
  duracao text,
  carga_horaria text,
  selo_mec boolean not null default false,
  imagem_url text,
  imagem_capa_url text,
  grade_curricular text,
  blocos_conteudo text,
  created_at timestamptz not null default now()
);
alter table public.cursos_cadastrados enable row level security;
drop policy if exists "cursos_cadastrados: leitura publica" on public.cursos_cadastrados;
create policy "cursos_cadastrados: leitura publica" on public.cursos_cadastrados for select to anon, authenticated using (true);
drop policy if exists "cursos_cadastrados: insert autenticado" on public.cursos_cadastrados;
create policy "cursos_cadastrados: insert autenticado" on public.cursos_cadastrados for insert to authenticated with check (true);
drop policy if exists "cursos_cadastrados: update autenticado" on public.cursos_cadastrados;
create policy "cursos_cadastrados: update autenticado" on public.cursos_cadastrados for update to authenticated using (true) with check (true);
drop policy if exists "cursos_cadastrados: delete autenticado" on public.cursos_cadastrados;
create policy "cursos_cadastrados: delete autenticado" on public.cursos_cadastrados for delete to authenticated using (true);

